REM starting backend service... 
cd backend && start npm run-script start:be 

REM starting frontend service... 
cd ../frontend && start npm run-script start:fe

REM starting graphql service... 
cd ../backend && start npm run-script start:gql
